version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=8080
      - MONGODB_URL=mongodb://mongo:27017/SongSchema
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
